# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the tf-owncloud branch
  push:
    tags:
      - '**'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      default_tag:
        description: 'tag name'
        required: true
        default: 'latest'
        
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  docker:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        # This action gets tag name from commit that triggered the action 
        # and puts it into an environment variable GIT_TAG_NAME.
        # It will also export is as an output named "tag".
      - name: Get tag name
        uses: olegtarasov/get-tag@v2
        id: tagName
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push the image - tag ${{ steps.tagName.outputs.tag }}
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: abouelsaad/owncloud:${{ steps.tagName.outputs.tag || github.event.inputs.default_tag }}
          
